### PR TITLE
ADD a parser for jquery.entwine

### PR DESCRIPTION
**Pull request by lingo**
https://github.com/hafriedlander/jquery.entwine

JQuery Entwine is heavily used by the SilverStripe Framework and CMS

https://www.silverstripe.org/

### CODE REVIEW

**Comment by DataTables** [comment]
Thanks for this! I hadn't encountered Entwine before.

Are you happy for this to be included under the MIT license?

**Comment by lingo** [comment]
Certainly, MIT is fine!

**Comment by DataTables** [comment]
Why was it closed?

**Comment by lingo** [comment]
Ah, because I clicked the wrong button :)

**Comment by DataTables** [comment]
Awesome - thanks! I'll get it deployed tot he site as soon as possible (might be a week or two).

**Comment by lingo** [comment]
Great, thank you!  Please can you comment here when it is deployed, and I'll let the SilverStripe community know.

**Pull request merged**
