### PR TITLE
Update jQuery.js

### PR DESCRIPTION
**Pull request by idnovate**
Fix error `events.hasOwnProperty is not a function`

### CODE REVIEW

**Comment by AllanJard** [comment]
Thanks for the PR! It has been a while since this repo has seen much activity :).

I'm not entirely clear why this is needed since `events` should be an object? Have you got an example page that shows the error?

**Comment by idnovate** [comment]
I thought it happens in all pages but actually I could only find this error in our page :confused:

https://www.idnovate.com/en/

**Comment by AllanJard** [comment]
Looks like it is something to do with how jQuery are now storing their events. I'm not sure why but it is not inherited from `Object`. Here is a little test with jQuery 3.5.1 showing the same thing: http://live.datatables.net/mopetiqi/1/edit .

**Comment by AllanJard** [comment]
Looks like it [was this commit](https://github.com/jquery/jquery/commit/413ff796ae16611777581e7657cb5ca76c3cfb1d) that when in for jQuery 3.5.0 that caused this.

Thanks for the patch here! I'll get it deployed on my server shortly.

**Pull request merged**
